# Generated by Django 5.0.3 on 2024-04-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popular',
            field=models.IntegerField(default=0, verbose_name='ko`rilganlar soni'),
        ),
    ]
